language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true

before_install:
  - sudo apt-get update -yq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes nomkl

install:
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION numpy matplotlib docopt requests pyyaml pytest
  - source activate testenv
  - conda install --yes pyproj gridgen coverage --channel=conda-forge
  - pip install .
  - pip install coveralls


before_script:
  - ls -al /usr/local/lib
  - ls -al /usr/local/include
  - conda list

script:
  - python check_pygridgen.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage run --source pygridgen check_pygridgen.py;
      coverage report -m;
      coveralls;
    fi
